name: Docker Image CI

on:
  create:
  push:
    branches: [master]
    paths: 
      - '.github/actions/*/action.yml'
      - '.github/workflows/docker-image-ci.yml'
      - '*/Dockerfile'
  pull_request:
    paths:
      - '.github/actions/*/action.yml'
      - '.github/workflows/docker-image-ci.yml'
      - '*/Dockerfile'

env:
  CONTAINER_REPOSITORIES: '["norionomura/swiftlint", "ghcr.io/norio-nomura/swiftlint"]'

jobs:

  build-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - swift_version: 5.6.3
            swift_version_aliases: ["5", "5.6"]
    env:
      LOAD: true
      PUSH: false
      SWIFTLINT_REVISION: 0.47.0

    steps:
    - uses: actions/checkout@v1

    - if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: |
        echo "LOAD=false" >> $GITHUB_ENV
        echo "PUSH=true" >> $GITHUB_ENV
        echo "SWIFTLINT_REVISION=${{ github.event.ref }}" >> $GITHUB_ENV

    - id: tags_for_latest
      uses: ./.github/actions/tags_for_latest
      with:
        repositories: ${{ env.CONTAINER_REPOSITORIES }}
        swift_version: ${{ toJSON(matrix.swift_version) }}
        swift_version_aliases: ${{ toJSON(matrix.swift_version_aliases) }}
        swiftlint_revision: ${{ toJSON(env.SWIFTLINT_REVISION) }}

    - run: echo "${{ steps.tags_for_latest.outputs.tags }}"

    - uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: norionomura
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      with:
        build-args: |
          BUILDER_IMAGE=swift:5.6-focal
          RUNTIME_IMAGE=swift:${{ matrix.swift_version }}-focal
          SWIFTLINT_REVISION=${{ env.SWIFTLINT_REVISION }}
        context: builder
        load: ${{ env.LOAD }}
        push: ${{ env.PUSH }}
        tags: ${{ steps.tags_for_latest.outputs.tags }}

    - run: docker run norionomura/swiftlint:${{ env.SWIFTLINT_REVISION }} cat /usr/bin/swiftlint > swiftlint

    - uses: actions/upload-artifact@v2
      with:
        name: swiftlint
        path: swiftlint

  push:
    needs: build-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swift_version: ['5.5.0', '5.5.1', '5.5.2', '5.5.3', '5.6.0', '5.6.1', '5.6.2']
        include:
          - swift_version: '5.5.3'
            swift_version_aliases: ["5.5"]
    env:
      PUSH: false
      SWIFTLINT_REVISION: 0.47.0
 
    steps:
    - uses: actions/checkout@v1

    - uses: actions/download-artifact@v2
      with:
        name: swiftlint
        path: copier/swiftlint

    - if: github.event_name == 'create' && github.event.ref_type == 'tag'
      run: |
        echo "PUSH=true" >> $GITHUB_ENV
        echo "SWIFTLINT_REVISION=${{ github.event.ref }}" >> $GITHUB_ENV

    - id: tags_for_older
      uses: ./.github/actions/tags_for_older
      with:
        repositories: ${{ env.CONTAINER_REPOSITORIES }}
        swift_version: ${{ toJSON(matrix.swift_version) }}
        swift_version_aliases: ${{ toJSON(matrix.swift_version_aliases) }}
        swiftlint_revision: ${{ toJSON(env.SWIFTLINT_REVISION) }}

    - run: echo "${{ steps.tags_for_older.outputs.tags }}"

    - uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: norionomura
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      with:
        build-args: |
          RUNTIME_IMAGE=swift:${{ matrix.swift_version }}-focal
        context: copier
        push: ${{ env.PUSH }}
        tags: ${{ steps.tags_for_older.outputs.tags }}
